id = "amp-acp"
name = "Amp"
version = "0.3.7"
schema_version = 1
authors = ["tao12345666333"]
description = "Amp Agent for Zed"
repository = "https://github.com/tao12345666333/amp-acp"

[agent_servers.amp]
name = "Amp"
env = { AMP_API_KEY = "" }

[agent_servers.amp.targets.darwin-aarch64]
archive = "https://github.com/tao12345666333/amp-acp/releases/download/v0.3.7/amp-acp-darwin-aarch64.tar.gz"
cmd = "amp-acp"

[agent_servers.amp.targets.darwin-x86_64]
archive = "https://github.com/tao12345666333/amp-acp/releases/download/v0.3.7/amp-acp-darwin-x86_64.tar.gz"
cmd = "amp-acp"

[agent_servers.amp.targets.linux-x86_64]
archive = "https://github.com/tao12345666333/amp-acp/releases/download/v0.3.7/amp-acp-linux-x86_64.tar.gz"
cmd = "amp-acp"

[agent_servers.amp.targets.windows-x86_64]
archive = "https://github.com/tao12345666333/amp-acp/releases/download/v0.3.7/amp-acp-windows-x86_64.zip"
cmd = "amp-acp.exe"
